module OfficialFixtures

%default total

||| A source string copied from the Unicode MessageFormat Working Group's
||| LDML48.2 conformance snapshot.
public export
record Fixture where
  constructor MkFixture
  description : String
  source : String

||| A source string paired with its first expected data-model error category.
public export
record ErrorFixture where
  constructor MkErrorFixture
  description : String
  source : String
  expected : String

||| 114 well-formed syntax cases from test/tests/syntax.json.
public export
validSyntax : List Fixture
validSyntax = [
  MkFixture "message -> simple-message -> <empty>" "",
  MkFixture "message -> simple-message -> simple-start pattern -> simple-start-char" "a",
  MkFixture "message -> simple-message -> simple-start pattern -> simple-start-char pattern -> ..." "hello",
  MkFixture "message -> simple-message -> simple-start pattern -> escaped-char" "\\\\",
  MkFixture "message -> simple-message -> simple-start pattern -> 1*escaped-char" "\\\\\\{\\|\\}",
  MkFixture "message -> simple-message -> simple-start pattern -> simple-start-char pattern -> ... -> simple-start-char *text-char placeholder" "hello {world}",
  MkFixture "message -> simple-message -> simple-start pattern -> simple-start-char pattern -> ... -> simple-start-char *text-char placeholder" "hello {|world|}",
  MkFixture "message -> simple-message -> s simple-start pattern -> s simple-start-char pattern -> ..." "\n hello\t",
  MkFixture "(official fixture)" "hello {$place}",
  MkFixture "(official fixture)" "hello {$place-.}",
  MkFixture "(official fixture)" "hello {$place}",
  MkFixture "message -> simple-message -> simple-start pattern -> placeholder -> expression -> literal-expression -> \"{\" literal \"}\"" "{a}",
  MkFixture "... -> literal-expression -> \"{\" literal s annotation \"}\" -> \"{\" literal s function \"}\" -> \"{\" literal s \":\" identifier \"}\" -> \"{\" literal s \":\" name \"}\"" "{a :f}",
  MkFixture "... -> \"{\" literal s \":\" namespace \":\" name \"}\"" "{a :u:f}",
  MkFixture "message -> simple-message -> simple-start pattern -> placeholder -> expression -> variable-expression -> \"{\" variable \"}\"" "{$x}",
  MkFixture "... -> variable-expression -> \"{\" variable s annotation \"}\" -> \"{\" variable s function \"}\" -> \"{\" variable s \":\" identifier \"}\" -> \"{\" variable s \":\" name \"}\"" "{$x :f}",
  MkFixture "... -> \"{\" variable s \":\" namespace \":\" name \"}\"" "{$x :u:f}",
  MkFixture "... -> annotation-expression -> function -> \"{\" \":\" namespace \":\" name \"}\"" "{:u:f}",
  MkFixture "... -> annotation-expression -> function -> \"{\" \":\" name \"}\"" "{:f}",
  MkFixture "message -> complex-message -> complex-body -> quoted-pattern -> \"{{\" pattern \"}}\" -> \"{{\"\"}}\"" "{{}}",
  MkFixture "message -> simple-message -> simple-start pattern -> placeholder -> markup -> \"{\" \"#\" identifier \"}\"" "{#tag}",
  MkFixture "message -> complex-message -> *(declaration [s]) complex-body -> declaration complex-body -> input-declaration complex-body -> input variable-expression complex-body" ".input{$x}{{}}",
  MkFixture "message -> complex-message -> s *(declaration [s]) complex-body s -> s declaration complex-body s -> s input-declaration complex-body s -> s input variable-expression complex-body s" "\t.input{$x}{{}}\n",
  MkFixture "message -> complex-message -> *(declaration [s]) complex-body -> declaration declaration complex-body -> input-declaration input-declaration complex-body -> input variable-expression input variable-expression complex-body" ".input{$x}.input{$y}{{}}",
  MkFixture "message -> complex-message -> *(declaration [s]) complex-body -> declaration s declaration complex-body -> input-declaration s input-declaration complex-body -> input variable-expression s input variable-expression complex-body" ".input{$x} .input{$y}{{}}",
  MkFixture "message -> complex-message -> s *(declaration [s]) complex-body s -> s complex-body s" "  {{}}  ",
  MkFixture "message -> complex-message -> *(declaration [s]) complex-body -> declaration declaration complex-body -> local-declaration input-declaration complex-body -> local s variable [s] \"=\" [s] expression input variable-expression complex-body" ".local $x ={a}.input{$y}{{}}",
  MkFixture "message -> complex-message -> complex-body -> ... -> matcher -> match-statement variant -> match selector key quoted-pattern -> \".match\" variable literal quoted-pattern" ".local $a={a :f}.match $a a{{}}*{{}}",
  MkFixture "... input-declaration -> input s variable-expression ..." ".input {$x}{{}}",
  MkFixture "... local-declaration -> local s variable s \"=\" expression ..." ".local $x ={a}{{}}",
  MkFixture "... local-declaration -> local s variable \"=\" s expression ..." ".local $x= {a}{{}}",
  MkFixture "... local-declaration -> local s variable s \"=\" expression ..." ".local $x = {a}{{}}",
  MkFixture "input-declaration-like content in complex-message" "{{.input {$x}}}",
  MkFixture "local-declaration-like content in complex-message with leading whitespace" "{{ .local $x = {$y}}}",
  MkFixture "... matcher -> match-statement [s] variant -> match 1*([s] selector) variant -> match selector selector variant -> match selector selector variant key s key quoted-pattern" ".local $a={a :f}.local $b={b :f}.match $a $b a b{{}}* *{{}}",
  MkFixture "... matcher -> match-statement [s] variant -> match 1*([s] selector) variant -> match selector variant variant ..." ".local $a={a :f}.match $a a{{}}b{{}}*{{}}",
  MkFixture "... variant -> key s quoted-pattern -> ..." ".local $a={a :f}.match $a a {{}}*{{}}",
  MkFixture "... variant -> key s key s quoted-pattern -> ..." ".local $a={a :f}.local $b={b :f}.match $a $b a b {{}}* *{{}}",
  MkFixture "... key -> \"*\" ..." ".local $a={a :f}.match $a *{{}}",
  MkFixture "simple-message -> simple-start pattern -> placeholder -> expression -> literal-expression -> \"{\" s literal \"}\"" "{ a}",
  MkFixture "... literal-expression -> \"{\" literal s attribute \"}\" -> \"{\" literal s \"@\" identifier \"}\"" "{a @c}",
  MkFixture "... -> literal-expression -> \"{\" literal s \"}\"" "{a }",
  MkFixture "simple-message -> simple-start pattern -> placeholder -> expression -> variable-expression -> \"{\" s variable \"}\"" "{ $x}",
  MkFixture "... variable-expression -> \"{\" variable s attribute \"}\" -> \"{\" variable s \"@\" identifier \"}\"" "{$x @c}",
  MkFixture "... -> variable-expression -> \"{\" variable s \"}\"" "{$x }",
  MkFixture "simple-message -> simple-start pattern -> placeholder -> expression -> annotation-expression -> \"{\" s annotation \"}\"" "{ :f}",
  MkFixture "... annotation-expression -> \"{\" annotation s attribute \"}\" -> \"{\" annotation s \"@\" identifier \"}\"" "{:f @c}",
  MkFixture "... -> annotation-expression -> \"{\" annotation s \"}\"" "{:f }",
  MkFixture "message -> simple-message -> simple-start pattern -> placeholder -> markup -> \"{\" s \"#\" identifier \"}\"" "{ #a}",
  MkFixture "message -> simple-message -> simple-start pattern -> placeholder -> markup -> \"{\" \"#\" identifier option \"}\" -> \"{\" \"#\" identifier identifier \"=\" literal \"}\"" "{#tag foo=bar}",
  MkFixture "message -> simple-message -> simple-start pattern -> placeholder -> markup -> \"{\" \"#\" identifier attribute \"}\" -> \"{\" \"#\" identifier identifier \"=\" literal \"}\"" "{#a @c}",
  MkFixture "message -> simple-message -> simple-start pattern -> placeholder -> markup -> \"{\" \"#\" identifier s \"}\" -> \"{\" \"#\" identifier identifier \"=\" literal \"}\"" "{#a }",
  MkFixture "message -> simple-message -> simple-start pattern -> placeholder -> markup -> \"{\" \"#\" identifier \"/\" \"}\" -> \"{\" \"#\" identifier identifier \"=\" literal \"}\"" "{#a/}",
  MkFixture "message -> simple-message -> simple-start pattern -> placeholder -> markup -> \"{\" \"/\" identifier \"}\"" "{/a}",
  MkFixture "message -> simple-message -> simple-start pattern -> placeholder -> markup -> \"{\" s \"/\" identifier \"}\"" "{ /a}",
  MkFixture "message -> simple-message -> simple-start pattern -> placeholder -> markup -> \"{\" \"/\" identifier option \"}\"" "{/tag foo=bar}",
  MkFixture "message -> simple-message -> simple-start pattern -> placeholder -> markup -> \"{\" \"/\" identifier s \"}\"" "{/a }",
  MkFixture "... annotation-expression -> function -> \":\" identifier option" "{:f k=v}",
  MkFixture "... option -> identifier s \"=\" literal" "{:f k =v}",
  MkFixture "... option -> identifier \"=\" s literal" "{:f k= v}",
  MkFixture "... option -> identifier s \"=\" s literal" "{:f k = v}",
  MkFixture "... attribute -> \"@\" identifier \"=\" literal ..." "{a @c=d}",
  MkFixture "... attribute -> \"@\" identifier s \"=\" literal ..." "{a @c =d}",
  MkFixture "... attribute -> \"@\" identifier \"=\" s literal ..." "{a @c= d}",
  MkFixture "... attribute -> \"@\" identifier s \"=\" s literal ..." "{a @c = d}",
  MkFixture "... attribute -> \"@\" identifier s \"=\" s quoted-literal ..." "{42 @foo=|bar|}",
  MkFixture "... quoted-literal" "{||}",
  MkFixture "... quoted-literal" "{|a|}",
  MkFixture "... quoted-literal" "{|\\\\|}",
  MkFixture "... quoted-literal" "{|a\\\\\\{\\|\\}|}",
  MkFixture "... unquoted-literal" "{0}",
  MkFixture "... unquoted-literal" "{-0}",
  MkFixture "... unquoted-literal" "{1}",
  MkFixture "... unquoted-literal" "{11}",
  MkFixture "... unquoted-literal" "{0.1}",
  MkFixture "... unquoted-literal" "{0.12}",
  MkFixture "... unquoted-literal" "{0e1}",
  MkFixture "... unquoted-literal" "{0E1}",
  MkFixture "... unquoted-literal" "{0E-1}",
  MkFixture "... unquoted-literal" "{0E-1}",
  MkFixture "+ as unquoted-literal" "{+}",
  MkFixture "- as unquoted-literal" "{-}",
  MkFixture ". as unquoted-literal" "{·}",
  MkFixture "emoji as unquoted-literal" "{🥔}",
  MkFixture "emoji above U+FFFF as unquoted-literal, " "{🀄️}",
  MkFixture "multi-code-point emoji as unquoted-literal" "{🏳️‍🌈}",
  MkFixture "various characters as unquoted-literal" "{¡؝ᚁ​‐‰⁠⁪、ﷰ}",
  MkFixture "(official fixture)" "hello { world\t\n}",
  MkFixture "(official fixture)" "hello {　world\r}",
  MkFixture "(official fixture)" "{$one} and {$two}",
  MkFixture "(official fixture)" "{$one} et {$two}",
  MkFixture "(official fixture)" ".local $foo = {bar} {{bar {$foo}}}",
  MkFixture "(official fixture)" ".local $foo = {|bar|} {{bar {$foo}}}",
  MkFixture "(official fixture)" ".local $foo = {|bar|} {{bar {$foo}}}",
  MkFixture "(official fixture)" ".local $foo = {$bar} {{bar {$foo}}}",
  MkFixture "(official fixture)" ".local $foo = {$baz} .local $bar = {$foo} {{bar {$bar}}}",
  MkFixture "(official fixture)" ".input {$foo} {{bar {$foo}}}",
  MkFixture "(official fixture)" ".input {$foo} .local $bar = {$foo} {{bar {$bar}}}",
  MkFixture "(official fixture)" ".local $foo = {$baz} .local $bar = {$foo} {{bar {$bar}}}",
  MkFixture "(official fixture)" ".local $x = {42} .local $y = {$x} {{{$x} {$y}}}",
  MkFixture "(official fixture)" "{#tag}content",
  MkFixture "(official fixture)" "{#ns:tag}content{/ns:tag}",
  MkFixture "(official fixture)" "{/tag}content",
  MkFixture "(official fixture)" "{#tag foo=bar/}",
  MkFixture "(official fixture)" "{#tag a:foo=|foo| b:bar=$bar}",
  MkFixture "(official fixture)" "{42 @foo @bar=13}",
  MkFixture "(official fixture)" "{{trailing whitespace}} \n",
  MkFixture "NFC: text is not normalized" "Ḍ̇",
  MkFixture "NFC: variables are compared to each other as-if normalized; decl is non-normalized, use is" ".local $Ḍ̇ = {foo} {{{$Ḍ̇}}}",
  MkFixture "NFC: variables are compared to each other as-if normalized; decl is normalized, use isn't" ".local $Ḍ̇ = {foo} {{{$Ḍ̇}}}",
  MkFixture "NFC: variables are compared to each other as-if normalized; decl is normalized, use isn't" ".input {$Ḍ̇} {{{$Ḍ̇}}}",
  MkFixture "NFC: variables are compared to each other as-if normalized; decl is non-normalized, use is" ".input {$Ḍ̇} {{{$Ḍ̇}}}",
  MkFixture "NFC: variables are compared to each other as-if normalized; decl is non-normalized, use is; reordering" ".local $Ḍ̇ = {foo} {{{$Ḍ̇}}}",
  MkFixture "NFC: variables are compared to each other as-if normalized; decl is non-normalized, use is; special case mapping" ".local $Ǻ = {foo} {{{$Ǻ}}}"
  ]

||| 133 syntax-error cases from test/tests/syntax-errors.json.
public export
syntaxErrors : List Fixture
syntaxErrors = [
  MkFixture "(official fixture)" ".",
  MkFixture "(official fixture)" "{",
  MkFixture "(official fixture)" "}",
  MkFixture "(official fixture)" "{}",
  MkFixture "(official fixture)" "{{",
  MkFixture "(official fixture)" "{{}",
  MkFixture "(official fixture)" "{{}}}",
  MkFixture "(official fixture)" "{|foo| #markup}",
  MkFixture "(official fixture)" "{{missing end brace}",
  MkFixture "(official fixture)" "{{missing end braces",
  MkFixture "(official fixture)" "{{missing end {$braces",
  MkFixture "(official fixture)" "{{extra}} content",
  MkFixture "(official fixture)" "empty { } placeholder",
  MkFixture "(official fixture)" "missing space {42:func}",
  MkFixture "(official fixture)" "missing space {|foo|:func}",
  MkFixture "(official fixture)" "missing space {|foo|@bar}",
  MkFixture "(official fixture)" "missing space {:func@bar}",
  MkFixture "(official fixture)" "missing space {:func @bar@baz}",
  MkFixture "(official fixture)" "missing space {:func @bar=42@baz}",
  MkFixture "(official fixture)" "missing space {+reserved@bar}",
  MkFixture "(official fixture)" "missing space {&private@bar}",
  MkFixture "(official fixture)" "bad {:} placeholder",
  MkFixture "(official fixture)" "bad {\\u0000placeholder}",
  MkFixture "(official fixture)" "no-equal {|42| :number minimumFractionDigits 2}",
  MkFixture "(official fixture)" "bad {:placeholder option=}",
  MkFixture "(official fixture)" "bad {:placeholder option value}",
  MkFixture "(official fixture)" "bad {:placeholder option:value}",
  MkFixture "(official fixture)" "bad {:placeholder option}",
  MkFixture "(official fixture)" "bad {:placeholder:}",
  MkFixture "(official fixture)" "bad {::placeholder}",
  MkFixture "(official fixture)" "bad {:placeholder::foo}",
  MkFixture "(official fixture)" "bad {:placeholder option:=x}",
  MkFixture "(official fixture)" "bad {:placeholder :option=x}",
  MkFixture "(official fixture)" "bad {:placeholder option::x=y}",
  MkFixture "(official fixture)" "bad {$placeholder option}",
  MkFixture "(official fixture)" "bad {:placeholder @attribute=}",
  MkFixture "(official fixture)" "bad {:placeholder @attribute=@foo}",
  MkFixture "(official fixture)" "bad {:placeholder @attribute=$foo}",
  MkFixture "(official fixture)" "{ @misplaced = attribute }",
  MkFixture "(official fixture)" "no {placeholder end",
  MkFixture "(official fixture)" "no {$placeholder end",
  MkFixture "(official fixture)" "no {:placeholder end",
  MkFixture "(official fixture)" "no {|placeholder| end",
  MkFixture "(official fixture)" "no {|literal} end",
  MkFixture "(official fixture)" "no {|literal or placeholder end",
  MkFixture "(official fixture)" ".local bar = {|foo|} {{_}}",
  MkFixture "(official fixture)" ".local #bar = {|foo|} {{_}}",
  MkFixture "(official fixture)" ".local $bar {|foo|} {{_}}",
  MkFixture "(official fixture)" ".local $bar = |foo| {{_}}",
  MkFixture "(official fixture)" ".match {{foo}}",
  MkFixture "(official fixture)" ".match * {{foo}}",
  MkFixture "(official fixture)" ".match x * {{foo}}",
  MkFixture "(official fixture)" ".match |x| * {{foo}}",
  MkFixture "(official fixture)" ".match :x * {{foo}}",
  MkFixture "(official fixture)" ".match {$foo} * {{foo}}",
  MkFixture "(official fixture)" ".match {#foo} * {{foo}}",
  MkFixture "(official fixture)" ".input {$x :x} .match {$x} * {{foo}}",
  MkFixture "(official fixture)" ".input {$x :x} .match$x * {{foo}}",
  MkFixture "(official fixture)" ".input {$x :x} .match $x* {{foo}}",
  MkFixture "(official fixture)" ".input {$x :x} .match $x|x| {{foo}} * {{foo}}",
  MkFixture "(official fixture)" ".input {$x :x} .local $y = {y :y} .match $x$y * * {{foo}}",
  MkFixture "(official fixture)" ".input {$x :x} .local $y = {y :y} .match $x $y ** {{foo}}",
  MkFixture "(official fixture)" ".input {$x :x} .match $x",
  MkFixture "(official fixture)" ".input {$x :x} .match $x *",
  MkFixture "(official fixture)" ".input {$x :x} .match $x * foo",
  MkFixture "(official fixture)" ".input {$x :x} .match $x * {{foo}} extra",
  MkFixture "(official fixture)" ".n{a}{{}}",
  MkFixture "(official fixture)" "{^}",
  MkFixture "(official fixture)" "{!}",
  MkFixture "(official fixture)" ".n .{a}{{}}",
  MkFixture "(official fixture)" ".n. {a}{{}}",
  MkFixture "(official fixture)" ".n.{a}{b}{{}}",
  MkFixture "(official fixture)" "{!.}",
  MkFixture "(official fixture)" "{! .}",
  MkFixture "(official fixture)" "{%}",
  MkFixture "(official fixture)" "{*}",
  MkFixture "(official fixture)" "{<}",
  MkFixture "(official fixture)" "{>}",
  MkFixture "(official fixture)" "{?}",
  MkFixture "(official fixture)" "{~}",
  MkFixture "(official fixture)" "{^.}",
  MkFixture "(official fixture)" "{^ .}",
  MkFixture "(official fixture)" "{&}",
  MkFixture "(official fixture)" "{﷐}",
  MkFixture "(official fixture)" "{￾}",
  MkFixture "(official fixture)" "{!.\\{}",
  MkFixture "(official fixture)" "{!. \\{}",
  MkFixture "(official fixture)" "{!|a|}",
  MkFixture "(official fixture)" "foo {&private}",
  MkFixture "(official fixture)" "foo {?reserved @a @b=c}",
  MkFixture "(official fixture)" ".foo {42} {{bar}}",
  MkFixture "(official fixture)" ".foo{42}{{bar}}",
  MkFixture "(official fixture)" ".foo |}lit{| {42}{{bar}}",
  MkFixture "(official fixture)" ".i {1} {{}}",
  MkFixture "(official fixture)" ".l $y = {|bar|} {{}}",
  MkFixture "(official fixture)" ".l $x.y = {|bar|} {{}}",
  MkFixture "(official fixture)" "hello {|4.2| %number}",
  MkFixture "(official fixture)" "hello {|4.2| %n|um|ber}",
  MkFixture "(official fixture)" "hello {|4.2| &num|be|r}",
  MkFixture "(official fixture)" "hello {|4.2| ^num|be|r}",
  MkFixture "(official fixture)" "hello {|4.2| +num|be|r}",
  MkFixture "(official fixture)" "hello {|4.2| ?num|be||r|s}",
  MkFixture "(official fixture)" "hello {|foo| !number}",
  MkFixture "(official fixture)" "hello {|foo| *number}",
  MkFixture "(official fixture)" "hello {?number}",
  MkFixture "(official fixture)" "{<tag}",
  MkFixture "(official fixture)" ".local $bar = {$none ~plural} .match {foo :string}  * {{{$bar}}}",
  MkFixture "(official fixture)" "hello {|4.2| %num\\\\ber}",
  MkFixture "(official fixture)" "hello {|4.2| %num\\{be\\|r}",
  MkFixture "(official fixture)" "hello {|4.2| %num\\\\\\}ber}",
  MkFixture "(official fixture)" "hello {|4.2| !}",
  MkFixture "(official fixture)" "hello {|4.2| %}",
  MkFixture "(official fixture)" "hello {|4.2| *}",
  MkFixture "(official fixture)" "hello {|4.2| ^abc|123||5|\\\\}",
  MkFixture "(official fixture)" "hello {|4.2| ^ abc|123||5|\\\\}",
  MkFixture "(official fixture)" "hello {|4.2| ^ abc|123||5|\\\\ \\|def |3.14||2|}",
  MkFixture "(official fixture)" "hello {|4.2| ? }",
  MkFixture "(official fixture)" "hello {|4.2| %xyzz }",
  MkFixture "(official fixture)" "hello {|4.2| >xyzz   }",
  MkFixture "(official fixture)" "hello {$foo ~xyzz }",
  MkFixture "(official fixture)" "hello {$x   <xyzz   }",
  MkFixture "(official fixture)" "{>xyzz }",
  MkFixture "(official fixture)" "{  !xyzz   }",
  MkFixture "(official fixture)" "{~xyzz }",
  MkFixture "(official fixture)" "{ <xyzz   }",
  MkFixture "(official fixture)" "hello {|4.2| !xy z z }",
  MkFixture "(official fixture)" "hello {|4.2| *num \\\\ b er}",
  MkFixture "(official fixture)" "hello {|4.2| %num \\\\ b |3.14| r    }",
  MkFixture "(official fixture)" "hello {|4.2|    +num xx \\\\ b |3.14| r  }",
  MkFixture "(official fixture)" "hello {$foo    +num x \\\\ abcde |3.14| r  }",
  MkFixture "(official fixture)" "hello {$foo    >num x \\\\ abcde |aaa||3.14||42| r  }",
  MkFixture "(official fixture)" "hello {$foo    >num x \\\\ abcde |aaa||3.14| |42| r  }",
  MkFixture "(official fixture)" ".input{ $n ~ }{{{$n}}}"
  ]

||| 23 semantic-error cases from test/tests/data-model-errors.json.
public export
dataModelErrors : List ErrorFixture
dataModelErrors = [
  MkErrorFixture "(official fixture)" ".input {$foo :x} .match $foo * * {{foo}}" "variant-key-mismatch",
  MkErrorFixture "(official fixture)" ".input {$foo :x} .input {$bar :x} .match $foo $bar * {{foo}}" "variant-key-mismatch",
  MkErrorFixture "(official fixture)" ".input {$foo :x} .match $foo 1 {{_}}" "missing-fallback-variant",
  MkErrorFixture "(official fixture)" ".input {$foo :x} .match $foo other {{_}}" "missing-fallback-variant",
  MkErrorFixture "(official fixture)" ".input {$foo :x} .input {$bar :x} .match $foo $bar * 1 {{_}} 1 * {{_}}" "missing-fallback-variant",
  MkErrorFixture "(official fixture)" ".input {$foo} .match $foo one {{one}} * {{other}}" "missing-selector-annotation",
  MkErrorFixture "(official fixture)" ".local $foo = {$bar} .match $foo one {{one}} * {{other}}" "missing-selector-annotation",
  MkErrorFixture "(official fixture)" ".input {$bar} .local $foo = {$bar} .match $foo one {{one}} * {{other}}" "missing-selector-annotation",
  MkErrorFixture "(official fixture)" ".input {$foo} .input {$foo} {{_}}" "duplicate-declaration",
  MkErrorFixture "(official fixture)" ".input {$foo} .local $foo = {42} {{_}}" "duplicate-declaration",
  MkErrorFixture "(official fixture)" ".local $foo = {42} .input {$foo} {{_}}" "duplicate-declaration",
  MkErrorFixture "(official fixture)" ".local $foo = {:unknown} .local $foo = {42} {{_}}" "duplicate-declaration",
  MkErrorFixture "(official fixture)" ".local $foo = {$bar} .local $bar = {42} {{_}}" "duplicate-declaration",
  MkErrorFixture "(official fixture)" ".local $foo = {$foo} {{_}}" "duplicate-declaration",
  MkErrorFixture "(official fixture)" ".local $foo = {$bar} .local $bar = {$baz} {{_}}" "duplicate-declaration",
  MkErrorFixture "(official fixture)" ".local $foo = {$bar :func} .local $bar = {$baz} {{_}}" "duplicate-declaration",
  MkErrorFixture "(official fixture)" ".local $foo = {42 :func opt=$foo} {{_}}" "duplicate-declaration",
  MkErrorFixture "(official fixture)" ".local $foo = {42 :func opt=$bar} .local $bar = {42} {{_}}" "duplicate-declaration",
  MkErrorFixture "(official fixture)" "bad {:placeholder option=x option=x}" "duplicate-option-name",
  MkErrorFixture "(official fixture)" "bad {:placeholder ns:option=x ns:option=y}" "duplicate-option-name",
  MkErrorFixture "(official fixture)" ".input {$var :string} .match $var * {{The first default}} * {{The second default}}" "duplicate-variant",
  MkErrorFixture "(official fixture)" ".input {$x :string} .input {$y :string} .match $x $y * foo {{The first foo variant}} bar * {{The bar variant}} * |foo| {{The second foo variant}} * * {{The default variant}}" "duplicate-variant",
  MkErrorFixture "(official fixture)" ".local $star = {star :string} .match $star |*| {{Literal star}} * {{The default}}" "data-model-error"
  ]

